project:
  type: website

website:
  title: "CFI - Diagnostico Ecosistema Libro"
  navbar:
    logo: img/logo.png
    left:
      - text: Inicio
        href: index.qmd
      - text: "Ejes de analisis"
        href: tarjetas.qmd
      - text: "Diagnostico"
        menu:
          - text: "Diagnostico inicial"
            href:  diagnostico/diagnostico_incial.qmd
          - text: "Materiales complementarios"
            href:  diagnostico/materiales_complementarios.qmd
      - text: "Sobre nosotros"
        href: about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

